[dev]
    publish = "public" 

[build]
    publish = "public"

[[redirects]]
    from = "/"
    to = "/landing.html"
    status = 200

[[redirects]]
    from = "/signup"
    to = "/signup.html"
    status = 200

[[redirects]]
    from = "/login"
    to = "/login.html"
    status = 200

[[redirects]]
    from = "/teacher"
    to = "/teacher.html"
    status = 200

[[redirects]]
    from = "/teacher/lesson-editor"
    to = "/teacher/lesson-editor.html"
    status = 200

[[redirects]]
    from = "/student"
    to = "/student.html"
    status = 200

[[redirects]]
    from = "/forgot-password"
    to = "/forgot-password.html"
    status = 200

[[redirects]]
    from = "/reset-password-confirmation"
    to = "/reset-password-confirmation.html"
    status = 200

[[redirects]]
    from = "/*.html"
    to = "/404.html"
    status = 404

[[redirects]]
    from = "/teacher/classes/lessons"
    to = "/teacher/lessons.html"
    status = 200

[functions]
    directory = "functions/"